# Generated by Django 5.0.3 on 2024-05-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nombre_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bloque',
            table='Bloque',
        ),
        migrations.AlterModelTable(
            name='campus',
            table='Campus',
        ),
        migrations.AlterModelTable(
            name='facultad',
            table='Facultad',
        ),
    ]
