# Generated by Django 5.0.3 on 2024-05-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre_app', '0002_alter_bloque_table_alter_campus_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloque',
            name='latitud',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bloque',
            name='longitud',
            field=models.FloatField(default=0.0),
        ),
    ]
